### ISSUE TITLE
Idea for date search

### ISSUE THREAD

**Issue by djzombie84** [ytakahashi/google-date-range-search#10]
1.When searching between two datums. After the search, the field is reset to the current day. Is it possible to leave the date in after the search?

Or better

2.An extension perhaps.
Self buttons can make e.g.
01.01.2015 to 02.01.2015 that you can save this date as a button. That would be very useful. That would be great if that would go

**Comment by ytakahashi** [comment]
Hello @djzombie84, thank you for your suggestions.
Both sound good and I think `1` is easier to do. Let me think about how to do it.

**Comment by DieZone19** [comment]
That's a good idea. Practical , and I am glad :)

**Comment by ytakahashi** [comment]
Hi, I made a change in #13 to keep the date input after leaving.
I have submitted a new package (1.2.0) to the webstore, and it is now pending review.
I think it will be available in a few days, thank you for waiting!

**Comment by djzombie84** [comment]
Thank you

**Comment by ytakahashi** [comment]
1.2.0 is now available. Please update your extension. Thank you!

**Comment by djzombie84** [comment]
It works very well. Good job :)

**Comment by jimlad68** [comment]
Nice and simple add on, it would be nice to have MORE PRESETS (especially 4 years - a common look back period), better still to create/amend our own presets.

**Comment by ytakahashi** [comment]
@jimlad68 Hi, I have updated this plugin so that you can create custom presets.
The new version, 1.3.0, is now available. Thank you!

**Comment by jimlad68** [comment]
Brilliant, many thanks. If you wanted to develop more I suppose you could add Presets to Calendar Tab

**Comment by ytakahashi** [comment]
Thanks for the suggestion. I'll do it when I have time.
